In [1]:
import numpy as np

In [2]:
a=[1,4,6,3]
type(a)

list

In [4]:
na=np.array(a)
na


array([1, 4, 6, 3])

In [5]:
type(na)

numpy.ndarray

In [7]:
b=[[1,6,3,4],[23,21,67,45],[11,20,17,10]]
nb=np.array(b)
nb

array([[ 1,  6,  3,  4],
       [23, 21, 67, 45],
       [11, 20, 17, 10]])

In [8]:
c=np.arange(10)
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
d=np.arange(4,12)
d

array([ 4,  5,  6,  7,  8,  9, 10, 11])

In [10]:
e=np.arange(5,12,2)
e

array([ 5,  7,  9, 11])

In [11]:
f=np.linspace(1,10,5)
f

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [12]:
nb.size

12

In [13]:
nb.shape

(3, 4)

In [14]:
g=np.zeros(6)
g

array([0., 0., 0., 0., 0., 0.])

In [15]:
h=np.zeros((3,4))
h

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
i=np.random.rand(3,4)
i

array([[0.27496618, 0.07361217, 0.55987235, 0.1736867 ],
       [0.50726171, 0.51602299, 0.55189135, 0.5791929 ],
       [0.78652702, 0.77996372, 0.17695167, 0.97027442]])

In [18]:
j=np.random.randint(3,100,10)
j

array([29, 21, 99, 60, 21, 89, 96, 52, 69,  9])